name: Deploy

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

    - name: Deploy
      run: nx affected --target=deploy
