name: Deploy

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Deploy
      run: nx affected --target=deploy
