name: Install

on:
  push:
    branches: [init]
    paths: ['apps/client/**', 'libs/**/fe/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        env:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v2
        env:
          cache-name: node-modules-npm
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Npm install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Deploy
        env:
          CLIENT_INIT_DEPLOY_KEY: ${{ secrets.CLIENT_INIT_DEPLOY_KEY }}
          CLIENT_2_INIT_DEPLOY_KEY: ${{ secrets.CLIENT_INIT_DEPLOY_KEY }}
        run: |
          npx nx affected \
          --target=deploy \
          --base=${{ github.event.before }} \
          --head=${{ github.event.after }} \
          --args="\
          --client-init-deploy-key=$CLIENT_INIT_DEPLOY_KEY\
          --client-2-init-deploy-key=$CLIENT_2_INIT_DEPLOY_KEY\
          "
