name: Install

on:
  push:
    branches: [master]
    paths: ['apps/client*/**', 'libs/**/fe/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        env:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v2
        env:
          cache-name: node-modules-npm
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}

      - name: Npm install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Patch version
        run: node ./.github/hooks/patch-version

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "patch version [skip ci]"
          git push origin HEAD:${{ github.event.pull_request.base.ref }}

      - name: Affected build
        env:
          before-sha: ${{ github.event.before }}
          after-sha: ${{ github.event.after }}
        run: |
          npx nx affected \
          --target=build \
          --base=${{ env.before-sha }} \
          --head=${{ env.after-sha }} \

      - name: Affected deploy
        env:
          before-sha: ${{ github.event.before }}
          after-sha: ${{ github.event.after }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          CLIENT_SITE_ID: ${{ secrets.PROD_CLIENT_SITE_ID }}
          CLIENT_2_SITE_ID: ${{ secrets.PROD_CLIENT_2_SITE_ID }}
        run: |
          npx nx affected \
          --target=deploy \
          --base=${{ env.before-sha }} \
          --head=${{ env.after-sha }} \
          --NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN \
          --CLIENT_SITE_ID=$CLIENT_SITE_ID \
          --CLIENT_2_SITE_ID=$CLIENT_2_SITE_ID \
